### ISSUE TITLE
[Assignment 1 - Login / SignUp] 기능 구현

### ISSUE THREAD

**Issue by NamJwong** [NamJwong/wanted-pre-onboarding-challenge-fe-1#8]
# Todos
- 회원가입 이메일/비밀번호 유효성 검사 기능 구현
  - [ ] 유효성 검사 방식 간단히 조사해보기
  - [x] 유효성 검사 방식 선택하기
- [x] api 연결
- [x] 토큰 존재 유무에 따른 자동 로그인 구현

# Memo
- Input 컴포넌트에 type 설정할 수 있게 해서 비밀번호 암호화 시키는 것은 시간이 없는데 구현 사항에 명시되어 있지 않아 미루겠다 ..
